language: ruby
rvm:
  - 1.9.3
before_install:
  - gem install bundler
before_script:
  - "rake"
  - bash build/post_build.sh
env:
  global:
    - secure: "tz123mqYYo9ObA64k/sfl3PasuPSmOVuvBlPWpIWW8lOxSLQeyMS4I/QUo2KE14jItlCT++Gw7CsQwF6Y+P1FzJgfWJXLcltZXvykZM5x9WsbZCsulFUbnJKiPqoqY34nMupBQ+HBADiDIQNGBkRipr2rPoHuQ1H/b7aQV1Ai5w="
branches:
  except:
    - gh-pages
script:
  - bash build/gh-pages-report.sh