# site info
name: Frontrend
description: for Front-end lovers.
url: http://frontrend.github.io
sitename: Frontrend powered by CyberAgent, Inc.
tagline: The CyberAgent Frontrend Meetup is about everything frontend technology.
title: Frontrend
author: Frontrend

# jekyll config
permalink: /blog/:title
markdown: rdiscount
pygments: true